import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, ChevronRight, LockKeyhole, Package, FileText, Phone, Clock } from "lucide-react";
import { toast } from "sonner";
import { Button, Dialog, DialogContent, DialogTitle, DialogDescription } from "./checkout-ui";
import { apiGet, apiPatch, formatApiError, formatINR } from "../lib/api";
import type { CommerceOrder, CommerceOverview, DraftResponse, QuoteLine, TimelineEntry } from "../lib/checkout-types";

type Lane = "paid_orders" | "checkout_drafts" | "earlier_orders";
type Selection = { kind: "draft" | "order"; id: string } | null;
const date = (value: string) => value ? new Date(value).toLocaleString("en-IN") : "Not recorded";

export default function AdminCommerce({ onChange }: { onChange?: () => void }) {
  const [lane, setLane] = useState<Lane>("paid_orders");
  const [selected, setSelected] = useState<Selection>(null);
  const client = useQueryClient();
  const overview = useQuery({ queryKey: ["admin-commerce"], queryFn: () => apiGet<CommerceOverview>("/api/admin/commerce"), refetchInterval: 15000, refetchOnWindowFocus: true, retry: false });
  const detail = useQuery({ queryKey: ["admin-order-detail", selected?.id], queryFn: () => apiGet<CommerceOrder>(`/api/admin/commerce/orders/${selected?.id}`), enabled: selected?.kind === "order", staleTime: 0, refetchInterval: 15000, retry: false });
  const draft = selected?.kind === "draft" ? overview.data?.checkout_drafts.find(item => item.id === selected.id) : undefined;
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => apiPatch<unknown>(`/api/admin/orders/${id}`, { status }), onSuccess: () => {
    void client.invalidateQueries({ queryKey: ["admin-commerce"] }); void client.invalidateQueries({ queryKey: ["admin-order-detail"] }); onChange?.(); toast.success("Pickup status updated. Payment record unchanged.");
  }, onError: error => toast.error(formatApiError(error)) });
  const lanes: { key: Lane; label: string }[] = [{ key: "paid_orders", label: "Paid orders" }, { key: "checkout_drafts", label: "Checkout drafts" }, { key: "earlier_orders", label: "Earlier orders" }];
  return <div className="commerce-panel space-y-5" data-testid="commerce-panel">
    <div className="flex justify-between gap-4 items-start"><div><h2 className="font-heading text-2xl font-bold" data-testid="commerce-title">Orders & payment records</h2><p className="text-xs text-slate-500 mt-2" data-testid="commerce-refresh-status">{overview.data ? `Checked ${date(overview.data.checked_at)} · refreshes every 15 seconds · latest 100 per section` : "Checking records…"}</p></div><Button variant="outline" size="sm" onClick={() => void overview.refetch()} disabled={overview.isFetching} data-testid="commerce-refresh"><RefreshCw size={15} className="mr-2" />Refresh</Button></div>
    <div className="flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900" data-testid="commerce-lock-notice"><LockKeyhole size={19} className="shrink-0" /><p>Only provider-confirmed full payments enter Paid orders. Checkout drafts are not orders. PhonePe and WhatsApp are not connected; no payments or invoices are being sent.</p></div>
    <div className="flex gap-2 flex-wrap" data-testid="commerce-lanes">{lanes.map(item => <Button key={item.key} variant={lane === item.key ? "default" : "outline"} onClick={() => { setLane(item.key); setSelected(null); }} data-testid={`commerce-lane-${item.key.replace(/_/g, "-")}`}>{item.label} · {overview.data?.[item.key].length ?? 0}</Button>)}</div>
    {overview.isPending && <p data-testid="commerce-loading">Loading records…</p>}
    {overview.isError && <p className="text-red-700" role="alert" data-testid="commerce-error">{formatApiError(overview.error)}. Use Refresh to try again.</p>}
    {overview.data && <>
      {overview.data[lane].length === 0 && <div className="bg-white border border-dashed rounded-xl p-10 text-center" data-testid="commerce-empty"><Package className="mx-auto text-slate-300 mb-3" size={35} /><h3 className="font-semibold">{lane === "paid_orders" ? "No provider-confirmed paid orders" : lane === "checkout_drafts" ? "No active checkout drafts" : "No earlier orders"}</h3><p className="text-sm text-slate-500 mt-2">{lane === "paid_orders" ? "Unverified payments and saved drafts never appear as paid orders." : "Records will appear here when available."}</p></div>}
      {lane === "checkout_drafts" ? overview.data.checkout_drafts.map(item => <button key={item.id} className="w-full text-left border rounded-lg bg-white p-5 hover:border-amber-600 flex justify-between gap-3" onClick={() => setSelected({ kind: "draft", id: item.id })} data-testid={`commerce-draft-${item.id}`}><div><strong className="font-mono text-sm">{item.reference}</strong><p className="text-sm mt-2">{item.customer_name} · {item.customer_phone}</p><p className="text-xs text-slate-500 mt-1">Not an order · WhatsApp unverified · Payment not started</p></div><div className="text-right shrink-0"><strong className="text-amber-700">{formatINR(item.total_amount)}</strong><ChevronRight size={18} className="ml-auto mt-3" /></div></button>) : overview.data[lane].map(item => <button key={item.id} className="w-full text-left border rounded-lg bg-white p-5 hover:border-amber-600 flex justify-between gap-3" onClick={() => setSelected({ kind: "order", id: item.id })} data-testid={`commerce-order-${item.id}`}><div><strong className="font-mono text-sm">{item.order_code}</strong><p className="text-sm mt-2">{item.customer_name} · {item.customer_phone}</p><p className="text-xs text-slate-500 mt-1">{item.provider_confirmed ? "Provider-confirmed full payment" : "Earlier record · not provider-confirmed"} · {item.status}</p></div><div className="text-right shrink-0"><strong className="text-amber-700">{formatINR(item.total_amount)}</strong><ChevronRight size={18} className="ml-auto mt-3" /></div></button>)}
    </>}
    <Dialog open={selected !== null} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="max-w-3xl max-h-[88vh] overflow-y-auto" data-testid="commerce-details">
      <DialogTitle data-testid="commerce-detail-title">{draft?.reference ?? (selected?.kind === "order" ? detail.data?.order_code : "Checkout draft") ?? "Order details"}</DialogTitle><DialogDescription data-testid="commerce-detail-description">{selected?.kind === "draft" ? "Nonpayable checkout draft. No order, payment or invoice has been created." : "Recorded materials, customer contact and payment information. Payment records are read-only."}</DialogDescription>
      {draft && <DraftDetails draft={draft} />}
      {selected?.kind === "draft" && !draft && <p data-testid="commerce-draft-unavailable">This draft has expired or is no longer available.</p>}
      {selected?.kind === "order" && detail.isPending && <p data-testid="commerce-detail-loading">Loading order…</p>}
      {selected?.kind === "order" && detail.isError && <p role="alert" data-testid="commerce-detail-error">{formatApiError(detail.error)}</p>}
      {selected?.kind === "order" && detail.data && <OrderDetails order={detail.data} updating={update.isPending} onUpdate={status => { const order = detail.data; if (order) update.mutate({ id: order.id, status }); }} />}
    </DialogContent></Dialog>
  </div>;
}

function Field({ id, label, value }: { id: string; label: string; value: string }) { return <div data-testid={`detail-${id}`}><dt className="text-xs text-slate-500">{label}</dt><dd className="font-medium text-sm mt-1 break-words">{value}</dd></div>; }
function Materials({ items }: { items: QuoteLine[] }) { return <section className="border-t pt-4 space-y-3"><h3 className="font-bold flex items-center gap-2" data-testid="detail-materials-title"><Package size={17} />Materials & charges</h3>{items.map((item, index) => <div key={`${item.product_id}-${item.brand_id}-${index}`} className="bg-slate-50 p-3 rounded text-sm" data-testid={`detail-material-${index}`}><div className="flex justify-between gap-3"><strong>{item.product_title}</strong><strong>{formatINR(item.subtotal_ex_gst + item.gst_amount + item.hamali_amount)}</strong></div><p className="text-slate-600 mt-1">{item.brand_name} · {item.quantity} {item.unit} × {formatINR(item.unit_price)}</p><p className="text-xs text-slate-500 mt-2">HSN {item.hsn_code || "not recorded"} · GST {item.gst_rate}% / {formatINR(item.gst_amount)} · Loading {formatINR(item.hamali_amount)}</p></div>)}</section>; }
function Timeline({ entries }: { entries: TimelineEntry[] }) { return <section className="border-t pt-4"><h3 className="font-bold flex gap-2 items-center" data-testid="detail-timeline-title"><Clock size={17} />Recorded activity</h3>{entries.length ? entries.map((entry, index) => <div className="border-l-2 border-amber-200 pl-3 mt-3 text-sm" key={`${entry.at}-${index}`} data-testid={`detail-activity-${index}`}><p>{entry.description}</p><p className="text-xs text-slate-500 mt-1">{date(entry.at)}</p></div>) : <p className="text-sm text-slate-500 mt-2" data-testid="detail-no-history">No detailed activity history was recorded for this earlier order.</p>}</section>; }
function DraftDetails({ draft }: { draft: DraftResponse }) { return <div className="space-y-5"><dl className="grid grid-cols-2 gap-4"><Field id="customer-name" label="Customer" value={draft.customer_name} /><Field id="customer-phone" label="WhatsApp number · unverified" value={draft.customer_phone} /><Field id="fulfillment" label="Fulfilment" value="Shop pickup only · No delivery" /><Field id="payment-status" label="Payment" value="Not started · ₹0 collected" /><Field id="consent" label="WhatsApp messaging consent" value={draft.whatsapp_consent ? "Provided" : "Not provided"} /><Field id="expires" label="Draft expires" value={date(draft.expires_at)} /></dl><Materials items={draft.items} /><dl className="grid grid-cols-2 gap-4"><Field id="total" label="Full quoted total (100%)" value={formatINR(draft.total_amount)} /><Field id="notes" label="Pickup notes" value={draft.notes || "None"} /><Field id="invoice" label="Invoice" value="Not issued · no verified payment" /><Field id="created" label="Created" value={date(draft.created_at)} /></dl><Timeline entries={draft.timeline} /></div>; }
function OrderDetails({ order, onUpdate, updating }: { order: CommerceOrder; onUpdate: (status: string) => void; updating: boolean }) {
  const next: Record<string, string> = { Paid: "Preparing", Preparing: "ReadyForPickup", ReadyForPickup: "Completed" };
  return <div className="space-y-5"><div className={`rounded p-3 text-sm ${order.provider_confirmed ? "bg-green-50 text-green-800" : "bg-amber-50 text-amber-900"}`} data-testid="detail-payment-trust">{order.provider_confirmed ? "Full payment confirmed by provider." : "Earlier order. Any old manual payment flag is historical—not a PhonePe confirmation."}</div><dl className="grid grid-cols-2 gap-4"><Field id="customer-name" label="Customer" value={order.customer_name} /><Field id="customer-phone" label="Customer phone" value={order.customer_phone} /><Field id="order-status" label="Pickup / order status" value={order.status} /><Field id="payment-status" label="Payment status" value={order.provider_confirmed ? "COMPLETED" : "Not provider-confirmed"} /><Field id="provider" label="Payment provider" value={order.payment.provider || "Not recorded"} /><Field id="transaction" label="Provider transaction reference" value={order.payment.provider_payment_id || "Not recorded"} /><Field id="utr" label="Recorded UTR" value={order.payment.utr_ref || "Not recorded"} /><Field id="payment-method" label="Payment method" value={order.payment.method || "Not recorded"} /><Field id="payment-date" label="Recorded verification time" value={date(order.payment.verified_at)} /><Field id="created" label="Order created" value={date(order.created_at)} /></dl><Materials items={order.items} /><dl className="grid grid-cols-2 gap-4"><Field id="total" label="Order total" value={formatINR(order.total_amount)} /><Field id="collected" label="Provider-confirmed amount" value={order.provider_confirmed ? formatINR(order.payment.amount_minor / 100) : "No provider-confirmed amount recorded"} /><Field id="historic-advance" label="Historical payment requirement" value={`${order.advance_percent}% · ${formatINR(order.advance_amount)}`} /><Field id="historic-balance" label="Recorded balance" value={formatINR(order.balance_amount)} /><Field id="invoice" label="WhatsApp invoice status" value={order.invoice_status.replace(/_/g, " ")} /><Field id="refund" label="Refund status" value={order.refund_status.replace(/_/g, " ")} /><Field id="notes" label="Pickup notes" value={order.notes || "None"} /></dl><div className="flex flex-wrap gap-3"><Button disabled variant="outline" data-testid="detail-send-invoice"><FileText size={15} className="mr-2" />Invoice delivery not connected</Button><Button disabled variant="outline" data-testid="detail-refund">Refund processing not connected</Button>{order.provider_confirmed && next[order.status] && <Button disabled={updating} onClick={() => onUpdate(next[order.status])} data-testid="detail-next-pickup">Mark {next[order.status]}</Button>}<a href={`tel:${order.customer_phone.replace(/[^+\d]/g, "")}`} className="inline-flex items-center gap-1 text-sm text-amber-700 font-semibold" data-testid="detail-call-customer"><Phone size={15} />Call customer</a></div><Timeline entries={order.timeline} /></div>;
}